### ISSUE TITLE
Cannot unzip your compressed files

### ISSUE THREAD

**Issue by happygirlzt** [SAILResearch/replication-duplicates_classical_realistic#3]
Hi there, firstly, thank you for your amazing work!

I tried to download and use your code, however, I cannot unzip it. I have no idea how to use these compressed files. Should I download them all? The source code.zip only contains a readme file.
<img width="1197" alt="截屏2021-02-16 21 30 35" src="https://user-images.githubusercontent.com/15061984/108069605-8432d680-709e-11eb-9b8a-8c60ef795651.png"> I also tried to unzip parts of these files. However, none of them succeeded. Could I know how to use your repo? Many thanks in advance!
<img width="847" alt="截屏2021-02-16 21 33 14" src="https://user-images.githubusercontent.com/15061984/108069661-94e34c80-709e-11eb-93e3-afa14f5582a7.png">

**Comment by golivax** [comment]
Hi @happygirlzt. Thanks for your interest in our work and apologies for the delay in getting back to you. So these are split tar.gz files (check https://unix.stackexchange.com/questions/61774/create-a-tar-archive-split-into-blocks-of-a-maximum-size). To uncompress the whole thing, you should download all parts and then run: `cat replication_package_realistic_vs_classical.tar.gz.* | tar xzvf -`

**Comment by happygirlzt** [comment]
Oh, many thanks for your help. 👯
